### ISSUE TITLE
Typo in oe_webtools_maps.info.yml and missing dependency in composer.json

### ISSUE THREAD

**Issue by kp77** [openeuropa/oe_webtools#73]
When installing oe_webtools_maps the geofield dependency is not enabled, because there is a typo in oe_webtools_maps.info.yml.

https://github.com/openeuropa/oe_webtools/blob/8feb05698a2d61b244fb9d1c3140878446520995/modules/oe_webtools_maps/oe_webtools_maps.info.yml#L8

After the typo is fixed, enabling the module gives the following error, because the geofield module is not required by composer.json:

`Unable to install modules: module 'oe_webtools_maps' is missing its dependency module geofield.`

**Comment by brummbar** [comment]
Hello @kp77 , thanks for the bug report. We will fix the typo and add some lines in the README regarding the dependency. Since this is a submodule, we cannot put the geofield module in the composer.json required section, as it would require it in every project, even if the maps submodule is not being enabled. So it needs to be required in the project composer json.

**Comment by kp77** [comment]
Hi @brummbar , yes it makes sense to not require it for the whole project. The typo fix and a few words in readme sounds good. It was just confusing because I assumed the dependency was enabled as there were no errors when I installed the module. Thanks!

**Comment by brummbar** [comment]
Fixed by #106 .
